name: keyboard_avoider2
description: A lightweight alternative to the Scaffold widget for avoiding the on-screen software keyboard. Automatically scrolls obscured TextField child widgets into view on focus.
version: 0.4.0
homepage: https://github.com/LahaLuhem/keyboard_avoider2

environment:
  flutter: ">=3.0.0"
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
